### ISSUE TITLE
Request: Logging players!

### ISSUE THREAD

**Issue by TomLewis** [Ugleh/RedstoneProximitySensor#12]
Request to log players that come in proximity as a setting, then this can be an intruder sensor that shows shows been in proximity, it could be showed as a GUI with player heads, hover over the player heads for timestamp of when they were there, the GUI is sorted by most recent first.
With its own permission/toggle.

Thanks!

**Comment by Ugleh** [comment]
I like the idea however it could create storage issues. I might make it into a separate addon.
