### ISSUE TITLE
Cannot measure distance between world_x and word_y

### ISSUE THREAD

**Issue by blackshot** [Ugleh/RedstoneProximitySensor#13]
im using PaperMC #88 1.15.2

04.02 01:52:03 [Server] WARN Task #30 for RedstoneProximitySensor v2.4.9 generated an exception
04.02 01:52:03 [Server] INFO java.lang.IllegalArgumentException: Cannot measure distance between world_nether and world
04.02 01:52:03 [Server] INFO at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.15.2.jar:git-Paper-88]
04.02 01:52:03 [Server] INFO at com.ugleh.redstoneproximitysensor.util.RPS.getNearbyEntities(RPS.java:64) ~[?:?]
04.02 01:52:03 [Server] INFO at com.ugleh.redstoneproximitysensor.util.RPS.run(RPS.java:132) ~[?:?]
04.02 01:52:03 [Server] INFO at com.ugleh.redstoneproximitysensor.util.RPSRunnable.run(RPSRunnable.java:23) ~[?:?]
04.02 01:52:03 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-88]
04.02 01:52:03 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-88]
04.02 01:52:03 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-88]
04.02 01:52:03 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-88]
04.02 01:52:03 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-88]
04.02 01:52:03 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-88]
04.02 01:52:03 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by Ugleh** [comment]
This may be a PaperMC issue and I do not support PaperMC at the moment, maybe in the future.
