### ISSUE TITLE
NullPointerException on sensors.yml load

### ISSUE THREAD

**Issue by Nishh** [Ugleh/RedstoneProximitySensor#2]
Error: https://paste.ubuntu.com/25735878/
Sensors.yml: https://paste.ubuntu.com/25735883/ (i didnt edited it)
Config: https://paste.ubuntu.com/25735887/

Server version: PaperSpigot 1.11.2
RPS version: 2.2.9 (latest)

**Comment by Ugleh** [comment]
For some reason this line of the sensors.yml

  8a8a9473-275f-46ad-8867-fdd1a4de92a8:
    acceptedEntities: []


does not have any more keys in it, just the ID and acceptedEntities:

I have no clue why that happened, I will look for the reason but in the mean time the next update will check to see if the keys its grabbing exists first and if it doesn't it may just delete the node.
