### ISSUE TITLE
Requesting a limit permission be added

### ISSUE THREAD

**Issue by TomLewis** [Ugleh/RedstoneProximitySensor#9]
Requesting a limit permission be added. rps.limit.10 to limit the amount of torches a player can make (To curb performance and abuse for OP things).
I do use this on 1.12.2 tho..

**Comment by Ugleh** [comment]
I will look into adding a limit, however I can not add it for 1.12.2 though.  I no longer support under 1.13.

**Comment by TomLewis** [comment]
Thanks man, I do plan to update, just not any time soon as I have legacy plugins, Will be good for future use mind.

**Comment by Ugleh** [comment]
Feature added in latest version.
